services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn social_media_api.wsgi:application --preload"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: socialapi
          property: connectionString

databases:
  - name: socialapi
    plan: free
